SERVER:
  host: '127.0.0.1'
  port: 5002

DATABASE:
  uri: ''
  db: 'senti'
  collection1: 'user'
  collection2: 'posts'
  colelction3: 'dashboard'

TWITTER:
  consumer_key: ''
  consumer_secret: ''
  api_key: ''
  api_secret: ''